### ISSUE TITLE
[Bug]: Docker 无法正常加载配置

### ISSUE THREAD

**Issue by Xm798** [XiaoMiku01/fansMedalHelper#108]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.6

### 运行环境

其它（请在下方说明）

### 运行架构

AMD64

### 部署方式

其它（请在下方说明）

### 粉丝牌数量

20

### 日志记录（可选）

```python
bili-fans  | Traceback (most recent call last):
bili-fans  |   File "/app/fansMedalHelper/index.py", line 11, in <module>
bili-fans  |     print(json.loads(users))
bili-fans  |   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
bili-fans  |     return _default_decoder.decode(s)
bili-fans  |   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
bili-fans  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
bili-fans  |   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
bili-fans  |     raise JSONDecodeError("Expecting value", s, err.value) from None
bili-fans  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### 补充说明（可选）

Docker 无法加载配置文件。
```python
print(os.environ.get("USERS")) # 正常输出
user = os.environ.get("USERS") # 正常输出
print(json.loads(user)) # 报错
```
在本地 Python 3.10，以上均能正常解析 json。

不确定是哪边的问题，现在 Docker 的入口感觉有些奇怪，没有必要在 python 中再调用一个 python。

**Comment by loveliveao** [comment]
我用docker部署后也无法正常使用，由于不清楚哪方面出的问题直接将完整log贴上，如果可能希望开发者能在百忙之中抽空优化下docker镜像，感激不尽。
```
.github/ISSUE_TEMPLATE/bug-report.yaml` | 109 ++++++++++++++
 .github/ISSUE_TEMPLATE/feat--.md       |  17 +++
 .github/workflows/sync.yml             |  20 +++
 README.md                              |  19 ++-
 code/requirements.txt                  |   3 +
 main.py                                |  78 ++++++----
 onepush/core.py                        |  22 ++-
 requirements.txt                       |   1 +
 s.yaml                                 |  42 ++++++
 src/api.py                             | 209 ++++++++++++++++++++-------
 src/user.py                            | 253 +++++++++++++++++++++++----------
 users.yaml                             |  12 +-
 12 files changed, 611 insertions(+), 174 deletions(-)
 create mode 100644 .github/ISSUE_TEMPLATE/bug-report.yaml
 create mode 100644 .github/ISSUE_TEMPLATE/feat--.md
 create mode 100644 .github/workflows/sync.yml
 create mode 100644 code/requirements.txt
 create mode 100644 s.yaml
2023-01-10 14:55:39  B站粉丝牌助手  使用内置定时器,开启定时任务,等待时间到达后执行
2023-01-11 02:02:00  B站粉丝牌助手  当前版本为: 0.3.6
2023-01-11 02:02:00  loveliveao  13545437 登录成功
2023-01-11 02:02:00  loveliveao  签到成功,本月签到次数: 5/31
2023-01-11 02:02:00  loveliveao  当前用户UL等级: 23 ,还差 5692259 经验升级
2023-01-11 02:02:01  loveliveao  共有 38 个牌子未满 1500 亲密度
2023-01-11 02:02:01  loveliveao  同步点赞任务开始....
2023-01-11 02:02:01  loveliveao  每日65分钟任务开始
2023-01-11 02:02:01  loveliveao  弹幕打卡任务开始....(预计 228 秒完成)
2023-01-11 02:02:01  loveliveao  应援团签到任务开始
2023-01-11 02:02:01  B站粉丝牌助手  time check failed
Traceback (most recent call last):

> File "/app/fansMedalHelper/main.py", line 80, in main
    await asyncio.gather(*startTasks)
          │       │       └ [<coroutine object BiliUser.start at 0x149573cedec0>]
          │       └ <function gather at 0x14957519ff70>
          └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>

  File "/app/fansMedalHelper/src/user.py", line 263, in start
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliUser.like_v3 at 0x149573cedc40>, <coroutine object BiliUser.watchinglive at 0x149573cc2c40>, <coroutin...
          │       └ <function gather at 0x14957519ff70>
          └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>

  File "/app/fansMedalHelper/src/user.py", line 322, in watchinglive
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliApi.heartbeat at 0x149573cc2bc0>, <coroutine object BiliApi.heartbeat at 0x149573c6ea40>, <coroutine o...
          │       └ <function gather at 0x14957519ff70>
          └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>

  File "/app/fansMedalHelper/src/api.py", line 434, in heartbeat
    return await self.__post(
                 └ <src.api.BiliApi object at 0x149573d53d00>

  File "/app/fansMedalHelper/src/api.py", line 73, in wrapper
    raise e

  File "/app/fansMedalHelper/src/api.py", line 62, in wrapper
    result = await func(*args, **kwargs)
                   │     │       └ {'data': {'access_key': '3bbe8e597751b6c8578b3ab4dda12e12', 'actionKey': 'appkey', 'appkey': '4409e2ce8ffd12b8', 'area_id': '...
                   │     └ (<src.api.BiliApi object at 0x149573d53d00>, 'https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBe...
                   └ <function BiliApi.__post at 0x1495744a70d0>

  File "/app/fansMedalHelper/src/api.py", line 135, in __post
    return self.__check_response(await resp.json())
           │                           │    └ <function ClientResponse.json at 0x1495745178b0>
           │                           └ <ClientResponse(https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBeat) [200 OK]>
           │                             <CIMultiDictProx...
           └ <src.api.BiliApi object at 0x149573d53d00>

  File "/app/fansMedalHelper/src/api.py", line 124, in __check_response
    raise BiliApiError(resp['code'], resp['message'])
          │            │             └ {'code': 1012002, 'message': 'time check failed', 'ttl': 1, 'data': {'heartbeat_interval': 60, 'timestamp': 1673402699, 'secr...
          │            └ {'code': 1012002, 'message': 'time check failed', 'ttl': 1, 'data': {'heartbeat_interval': 60, 'timestamp': 1673402699, 'secr...
          └ <class 'src.api.BiliApiError'>

src.api.BiliApiError: time check failed
2023-01-11 02:02:01  loveliveao  鹿乃ちゃん 房间弹幕打卡成功: （￣▽￣）. (1/0)
2023-01-11 02:02:01  loveliveao  鹿乃ちゃん 点赞成功 1/0
2023-01-11 02:02:01  loveliveao  任亦歌的应援团① 签到成功
2023-01-11 02:02:01  B站粉丝牌助手  任务执行失败: time check failed
2023-01-11 02:02:01  B站粉丝牌助手  【loveliveao】 签到成功,本月签到次数: 5/31
2023-01-11 02:02:01  B站粉丝牌助手  【loveliveao】 UL等级: 23 ,还差 5692259 经验升级
2023-01-11 02:02:01  B站粉丝牌助手  【loveliveao】 今日亲密度获取情况如下（20级以下）：
2023-01-11 02:02:01  B站粉丝牌助手  【1200以下】鹿乃ちゃん 神楽七奈Official 早睡健康长寿 TESTV官方频道 阿梓从小就很可爱等 38个
2023-01-11 02:02:01  B站粉丝牌助手  【当前佩戴】「小鹿包」(鹿乃ちゃん) 18 级 
2023-01-11 02:02:01  B站粉丝牌助手  今日已获取亲密度 100 (B站结算有延迟，请耐心等待)
2023-01-11 02:02:01  B站粉丝牌助手  距离下一级还需 245588 亲密度 预计需要 164 天 (2023-06-24,以每日 1500 亲密度计算)
2023-01-11 02:02:01  B站粉丝牌助手  错误日志：
2023-01-11 02:02:01  B站粉丝牌助手  ---
2023-01-11 02:02:01  B站粉丝牌助手  任务结束,等待下一次执行
```
