### ISSUE TITLE
[Bug]:显示Time check failed

### ISSUE THREAD

**Issue by Mirrordynamic** [XiaoMiku01/fansMedalHelper#123]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.6

### 运行环境

Windows (64)

### 运行架构

AMD64

### 部署方式

本地

### 粉丝牌数量

11

### 日志记录（可选）

```python
以下为部分运行日志：
2023-03-10 17:43:17  B站粉丝牌助手  time check failed
Traceback (most recent call last):

> File "c:\Users\Faith\fansMedalHelper\main.py", line 80, in main
    await asyncio.gather(*startTasks)
          │       │       └ [<coroutine object BiliUser.start at 0x0000021AF67564C0>]
          │       └ <function gather at 0x0000021AF5812C10>
          └ <module 'asyncio' from 'C:\\Users\\Faith\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\__init__.py'>

  File "c:\Users\Faith\fansMedalHelper\src\user.py", line 263, in start
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliUser.like_v3 at 0x0000021AF67560C0>, <coroutine object BiliUser.watchinglive at 0x0000021AF6756BC0>, <...
          │       └ <function gather at 0x0000021AF5812C10>
          └ <module 'asyncio' from 'C:\\Users\\Faith\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\__init__.py'>

  File "c:\Users\Faith\fansMedalHelper\src\user.py", line 322, in watchinglive
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliApi.heartbeat at 0x0000021AF6786EC0>, <coroutine object BiliApi.heartbeat at 0x0000021AF6786F40>, <cor...
          │       └ <function gather at 0x0000021AF5812C10>
          └ <module 'asyncio' from 'C:\\Users\\Faith\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\__init__.py'>

  File "c:\Users\Faith\fansMedalHelper\src\api.py", line 434, in heartbeat
    return await self.__post(
                 └ <src.api.BiliApi object at 0x0000021AF673A130>

  File "c:\Users\Faith\fansMedalHelper\src\api.py", line 73, in wrapper
    raise e

  File "c:\Users\Faith\fansMedalHelper\src\api.py", line 62, in wrapper
    result = await func(*args, **kwargs)
                   │     │       └ {'data': {'access_key': '74a168c989e7ddf360637236f8615b12', 'actionKey': 'appkey', 'appkey': '4409e2ce8ffd12b8', 'area_id': '...
                   │     └ (<src.api.BiliApi object at 0x0000021AF673A130>, 'https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHea...
                   └ <function BiliApi.__post at 0x0000021AF634F0D0>

  File "c:\Users\Faith\fansMedalHelper\src\api.py", line 135, in __post
    return self.__check_response(await resp.json())
           │                           │    └ <function ClientResponse.json at 0x0000021AF62A09D0>
           │                           └ <ClientResponse(https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBeat) [200 OK]>
           │                             <CIMultiDictProx...
           └ <src.api.BiliApi object at 0x0000021AF673A130>

  File "c:\Users\Faith\fansMedalHelper\src\api.py", line 124, in __check_response
    raise BiliApiError(resp['code'], resp['message'])
          │            │             └ {'code': 1012002, 'message': 'time check failed', 'ttl': 1, 'data': {'heartbeat_interval': 60, 'timestamp': 1678441366, 'secr...
          │            └ {'code': 1012002, 'message': 'time check failed', 'ttl': 1, 'data': {'heartbeat_interval': 60, 'timestamp': 1678441366, 'secr...
          └ <class 'src.api.BiliApiError'>

src.api.BiliApiError: time check failed
2023-03-10 17:43:18  B站粉丝牌助手  任务执行失败: time check failed
```

**Comment by XiaoMiku01** [comment]
系统时间不准

**Comment by Mirrordynamic** [comment]
感谢！
