### ISSUE TITLE
[Error]: 点赞和应援团签到任务都执行一个后，就连不上live-trace.bilibili.com了

### ISSUE THREAD

**Issue by deYangar** [XiaoMiku01/fansMedalHelper#144]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.7

### 运行环境

其它（请在下方说明）

### 运行架构

AMD64

### 部署方式

其它（请在下方说明）

### 粉丝牌数量

56

### 日志记录（可选）

```python
2023-09-12 10:00:00  B站粉丝牌助手  当前版本为: 0.3.7
2023-09-12 10:00:00  （用户名）  （抹除） 登录成功
2023-09-12 10:00:01  （用户名）  签到成功,本月签到次数: 12/30
2023-09-12 10:00:01  （用户名）  当前用户UL等级: 39 ,还差 20598598 经验升级
2023-09-12 10:00:01  （用户名）  共有 49 个牌子未满 1500 亲密度
2023-09-12 10:00:01  （用户名）  同步点赞任务开始....
2023-09-12 10:00:01  （用户名）  每日65分钟任务开始
2023-09-12 10:00:01  （用户名）  弹幕打卡任务开始....(预计 336 秒完成)
2023-09-12 10:00:01  （用户名）  应援团签到任务开始
2023-09-12 10:00:01  （用户名）  （抹除） 点赞成功 1/49
2023-09-12 10:00:02  （用户名）  （抹除）的应援团① 签到成功
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  B站粉丝牌助手  Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
                 │    │     │                  │       └ {'ssl': <ssl.SSLContext object at 0x7fc8c3befcc0>, 'family': <AddressFamily.AF_INET: 2>, 'proto': 6, 'flags': <AddressInfo.AI...
                 │    │     │                  └ (functools.partial(<class 'aiohttp.client_proto.ResponseHandler'>, loop=<_UnixSelectorEventLoop running=True closed=False deb...
                 │    │     └ <function BaseEventLoop.create_connection at 0x7fc8c4c30af0>
                 │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
                 └ <aiohttp.connector.TCPConnector object at 0x7fc8c3bddf10>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
          └ [ConnectionRefusedError(111, "Connect call failed ('0.0.0.0', 443)")]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
                 │    └ <function BaseEventLoop._connect_sock at 0x7fc8c4c30a60>
                 └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
          │    │            │     └ ('0.0.0.0', 443)
          │    │            └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
          │    └ <function BaseSelectorEventLoop.sock_connect at 0x7fc8c4bdaaf0>
          └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
                 └ <Future finished exception=ConnectionRefusedError(111, "Connect call failed ('0.0.0.0', 443)")>
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
                  └ 111
ConnectionRefusedError: [Errno 111] Connect call failed ('0.0.0.0', 443)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
> File "/app/fansMedalHelper/main.py", line 87, in main
    await asyncio.gather(*startTasks)
          │       │       └ [<coroutine object BiliUser.start at 0x7fc8c3bef340>]
          │       └ <function gather at 0x7fc8c4c25040>
          └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>
  File "/app/fansMedalHelper/src/user.py", line 263, in start
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliUser.like_v3 at 0x7fc8c3bef240>, <coroutine object BiliUser.watchinglive at 0x7fc8c3befc40>, <coroutin...
          │       └ <function gather at 0x7fc8c4c25040>
          └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>
  File "/app/fansMedalHelper/src/user.py", line 322, in watchinglive
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliApi.heartbeat at 0x7fc8c37869c0>, <coroutine object BiliApi.heartbeat at 0x7fc8c37867c0>, <coroutine o...
          │       └ <function gather at 0x7fc8c4c25040>
          └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>
  File "/app/fansMedalHelper/src/api.py", line 435, in heartbeat
    return await self.__post(
                 └ <src.api.BiliApi object at 0x7fc8c3bf4190>
  File "/app/fansMedalHelper/src/api.py", line 76, in wrapper
    raise e
  File "/app/fansMedalHelper/src/api.py", line 62, in wrapper
    result = await func(*args, **kwargs)
                   │     │       └ {'data': {（抹除）...
                   │     └ (<src.api.BiliApi object at 0x7fc8c3bf4190>, 'https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBe...
                   └ <function BiliApi.__post at 0x7fc8c408c5e0>
  File "/app/fansMedalHelper/src/api.py", line 134, in __post
    async with self.session.post(*args, **kwargs) as resp:
               │    │       │     │       └ {'data': {（抹除）...
               │    │       │     └ ('https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBeat',)
               │    │       └ <function ClientSession.post at 0x7fc8c4109dc0>
               │    └ <aiohttp.client.ClientSession object at 0x7fc8c3bdd9d0>
               └ <src.api.BiliApi object at 0x7fc8c3bf4190>
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
    │    │             │    └ <member '_coro' of '_BaseRequestContextManager' objects>
    │    │             └ <aiohttp.client._RequestContextManager object at 0x7fc8c34ce670>
    │    └ <member '_resp' of '_BaseRequestContextManager' objects>
    └ <aiohttp.client._RequestContextManager object at 0x7fc8c34ce670>
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
                 │    │          └ <function BaseConnector.connect at 0x7fc8c4152940>
                 │    └ <aiohttp.connector.TCPConnector object at 0x7fc8c3bddf10>
                 └ <aiohttp.client.ClientSession object at 0x7fc8c3bdd9d0>
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
                  │    │                  │    │       └ ClientTimeout(total=3, connect=None, sock_read=None, sock_connect=None)
                  │    │                  │    └ []
                  │    │                  └ <aiohttp.client_reqrep.ClientRequest object at 0x7fc8c34ce0d0>
                  │    └ <function TCPConnector._create_connection at 0x7fc8c4155430>
                  └ <aiohttp.connector.TCPConnector object at 0x7fc8c3bddf10>
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
                     │    │                         │    │       └ ClientTimeout(total=3, connect=None, sock_read=None, sock_connect=None)
                     │    │                         │    └ []
                     │    │                         └ <aiohttp.client_reqrep.ClientRequest object at 0x7fc8c34ce0d0>
                     │    └ <function TCPConnector._create_direct_connection at 0x7fc8c4155a60>
                     └ <aiohttp.connector.TCPConnector object at 0x7fc8c3bddf10>
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
          └ ClientConnectorError(ConnectionKey(host='live-trace.bilibili.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=No...
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                          │    └ <function TCPConnector._wrap_create_connection at 0x7fc8c4155700>
                          └ <aiohttp.connector.TCPConnector object at 0x7fc8c3bddf10>
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
          │            │   └ <property object at 0x7fc8c41b89a0>
          │            └ <aiohttp.client_reqrep.ClientRequest object at 0x7fc8c34ce0d0>
          └ <class 'aiohttp.client_exceptions.ClientConnectorError'>
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:04  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  （用户名）  API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  B站粉丝牌助手  任务执行失败: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
2023-09-12 10:00:05  B站粉丝牌助手  【（用户名）】 签到成功,本月签到次数: 12/30
2023-09-12 10:00:05  B站粉丝牌助手  【（用户名）】 UL等级: 39 ,还差 20598598 经验升级
2023-09-12 10:00:05  B站粉丝牌助手  【（用户名）】 今日亲密度获取情况如下（20级以下）：
2023-09-12 10:00:05  B站粉丝牌助手  【1200以下】（抹除）等 49个
2023-09-12 10:00:05  B站粉丝牌助手  【当前佩戴】「补给箱」(哔哩哔哩守望先锋赛事) 20 级 
2023-09-12 10:00:05  B站粉丝牌助手  错误日志：
2023-09-12 10:00:05  B站粉丝牌助手  ---
2023-09-12 10:00:05  B站粉丝牌助手  任务结束，等待下一次执行。
```

### 补充说明（可选）

linux x86_64 QTS 5.1.1 (20230815)
docker部署 版本20.10.22

换过Access_key也不行

**Comment by XiaoMiku01** [comment]
网络环境异常 live-trace.bilibili.com 可能被广告屏蔽插件屏蔽了

**Comment by deYangar** [comment]
![QQ截图20230912163559](https://github.com/XiaoMiku01/fansMedalHelper/assets/70438628/62088483-caf5-4b67-b70c-eee00e15d25f)
绝了
