### ISSUE TITLE
[Bug]: 错误代码

### ISSUE THREAD

**Issue by liuzilong9829** [XiaoMiku01/fansMedalHelper#148]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [x] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

 0.3.7

### 运行环境

其它（请在下方说明）

### 运行架构

其它

### 部署方式

阿里云函数

### 粉丝牌数量

200+

### 日志记录（可选）

```python
房间弹幕打卡成功: (￣3￣). (94/232)
c-65217e3f-722cc76d2ec04a06870d2023-10-08 00:00:352023-10-08 00:00:35  B站粉丝牌助手  bad timestamp request,timestamp:1696694375,watchtime:60
Traceback (most recent call last):

> File "/code/main.py", line 87, in main
    await asyncio.gather(*startTasks)
          │       │       └ [<coroutine object BiliUser.start at 0x7f5e6ffbbc40>]
          │       └ <function gather at 0x7f5e6cf93d30>
          └ <module 'asyncio' from '/var/fc/lang/python3.9/lib/python3.9/asyncio/__init__.py'>

  File "/code/src/user.py", line 263, in start
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliUser.like_v3 at 0x7f5e6ab46f40>, <coroutine object BiliUser.watchinglive at 0x7f5e697e8dc0>, <coroutin...
          │       └ <function gather at 0x7f5e6cf93d30>
          └ <module 'asyncio' from '/var/fc/lang/python3.9/lib/python3.9/asyncio/__init__.py'>

  File "/code/src/user.py", line 322, in watchinglive
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliApi.heartbeat at 0x7f5e69774d40>, <coroutine object BiliApi.heartbeat at 0x7f5e69774f40>, <coroutine o...
          │       └ <function gather at 0x7f5e6cf93d30>
          └ <module 'asyncio' from '/var/fc/lang/python3.9/lib/python3.9/asyncio/__init__.py'>

  File "/code/src/api.py", line 435, in heartbeat
    return await self.__post(
                 └ <src.api.BiliApi object at 0x7f5e6a8688e0>

  File "/code/src/api.py", line 73, in wrapper
    raise e

  File "/code/src/api.py", line 62, in wrapper
    result = await func(*args, **kwargs)
                   │     │       └ {'data': {'access_key': '', 'actionKey': 'appkey', 'appkey': '', 'area_id': '...
                   │     └ (<src.api.BiliApi object at 0x7f5e6a8688e0>, 'https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBe...
                   └ <function BiliApi.__post at 0x7f5e6a887ee0>

  File "/code/src/api.py", line 135, in __post
    return self.__check_response(await resp.json())
           │                           │    └ <function ClientResponse.json at 0x7f5e6abd6790>
           │                           └ <ClientResponse(https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBeat) [200 OK]>
           │                             <CIMultiDictProx...
           └ <src.api.BiliApi object at 0x7f5e6a8688e0>

  File "/code/src/api.py", line 124, in __check_response
    raise BiliApiError(resp['code'], resp['message'])
          │            │             └ {'code': 1012003, 'message': 'bad timestamp request,timestamp:1696694375,watchtime:60', 'ttl': 1, 'data': None}
          │            └ {'code': 1012003, 'message': 'bad timestamp request,timestamp:1696694375,watchtime:60', 'ttl': 1, 'data': None}
          └ <class 'src.api.BiliApiError'>

src.api.BiliApiError: bad timestamp request,timestamp:1696694375,watchtime:60
c-65217e3f-722cc76d2ec04a06870d2023-10-08 00:00:362023-10-08 00:00:36  B站粉丝牌助手  任务执行失败: bad timestamp request,timestamp:1696694375,watchtime:60
```

**Comment by XiaoMiku01** [comment]
本地时间不准导致的
