### ISSUE TITLE
[Bug]: BiliApiError: request was banned 【fixed!】

### ISSUE THREAD

**Issue by hnyqwqgh** [XiaoMiku01/fansMedalHelper#159]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.7

### 运行环境

Windows (64)

### 运行架构

None

### 部署方式

本地

### 粉丝牌数量

154

### 日志记录（可选）

```python
点赞任务异常
Traceback (most recent call last):

  File "D:\botfsp\fansMedalHelper\main.py", line 157, in <module>
    loop.run_until_complete(main())
    │    │                  └ <function main at 0x00000252E1E91360>
    │    └ <function BaseEventLoop.run_until_complete at 0x00000252E13CA950>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\27178\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000252E147B370>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\27178\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\27178\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000252E13D4430>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\27178\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000252DFB27910>
    └ <Handle Task.task_wakeup(<_GatheringFu... was banned')>)>

  File "C:\Users\27178\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<_GatheringFu... was banned')>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<_GatheringFu... was banned')>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<_GatheringFu... was banned')>)>

> File "D:\botfsp\fansMedalHelper\src\user.py", line 195, in like_v3
    await asyncio.gather(*allTasks)
          │       │       └ [<coroutine object BiliApi.likeInteractV3 at 0x00000252E1EBD3F0>, <coroutine object BiliApi.likeInteractV3 at 0x00000252E1EBD...
          │       └ <function gather at 0x00000252E13B1D80>
          └ <module 'asyncio' from 'C:\\Users\\27178\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\__init__.py'>

  File "D:\botfsp\fansMedalHelper\src\api.py", line 205, in likeInteractV3
    await self.__post(
          └ <src.api.BiliApi object at 0x00000252E1E72320>

  File "D:\botfsp\fansMedalHelper\src\api.py", line 73, in wrapper
    raise e

  File "D:\botfsp\fansMedalHelper\src\api.py", line 62, in wrapper
    result = await func(*args, **kwargs)
                   │     │       └ {'data': {'access_key': '·········', 'actionKey': 'appkey', 'anchor_id': ········, 'appkey': '···········...
                   │     └ (<src.api.BiliApi object at 0x00000252E1E72320>, 'https://api.live.bilibili.com/xlive/app-ucenter/v1/like_info_v3/like/likeRe...
                   └ <function BiliApi.__post at 0x00000252E1DE24D0>

  File "D:\botfsp\fansMedalHelper\src\api.py", line 135, in __post
    return self.__check_response(await resp.json())
           │                           │    └ <function ClientResponse.json at 0x00000252E1D66CB0>
           │                           └ <ClientResponse(https://api.live.bilibili.com/xlive/app-ucenter/v1/like_info_v3/like/likeReportV3) [412 Precondition Failed]>...
           └ <src.api.BiliApi object at 0x00000252E1E72320>

  File "D:\botfsp\fansMedalHelper\src\api.py", line 124, in __check_response
    raise BiliApiError(resp['code'], resp['message'])
          │            │             └ {'code': -412, 'message': 'request was banned', 'ttl': 1}
          │            └ {'code': -412, 'message': 'request was banned', 'ttl': 1}
          └ <class 'src.api.BiliApiError'>

src.api.BiliApiError: request was banned
```

### 补充说明（可选）

是我账号的问题咩，三个账号都报错。我看2022年的[issues#36](https://github.com/XiaoMiku01/fansMedalHelper/issues/36)好像是类似的报错（？）感谢大佬

**Comment by shanren200** [comment]
<img width="236" alt="企业微信截图_17053658723832" src="https://github.com/XiaoMiku01/fansMedalHelper/assets/60208500/066aea9d-c6cc-447a-a1bc-e747b629da70">

同样问题，今天刚发现

**Comment by Night1918** [comment]
同样问题
```
2024-01-16 02:00:00  B站粉丝牌助手  当前版本为: 0.3.7
2024-01-16 02:00:01  夜辰哒哒哒  439240749 登录成功
2024-01-16 02:00:01  夜辰哒哒哒  签到成功,本月签到次数: 15/31
2024-01-16 02:00:01  夜辰哒哒哒  当前用户UL等级: 12 ,还差 748694 经验升级
2024-01-16 02:00:01  夜辰哒哒哒  共有 16 个牌子未满 1500 亲密度
2024-01-16 02:00:01  夜辰哒哒哒  异步点赞任务开始....
2024-01-16 02:00:01  夜辰哒哒哒  每日75分钟任务开始
2024-01-16 02:00:01  夜辰哒哒哒  弹幕打卡任务开始....(预计 102 秒完成)
2024-01-16 02:00:01  夜辰哒哒哒  应援团签到任务开始
2024-01-16 02:00:01  夜辰哒哒哒  点赞任务异常
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7feb5d8aea60>
    └ <Thread(ThreadPoolExecutor-0_0, started 140648835726136)>
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7feb5d8ae790>
    └ <Thread(ThreadPoolExecutor-0_0, started 140648835726136)>
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started 140648835726136)>
    │    │        │    └ (<weakref at 0x7feb5be8e540; to 'ThreadPoolExecutor' at 0x7feb5be7e5b0>, <_queue.SimpleQueue object at 0x7feb5be8b2c0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started 140648835726136)>
    │    └ <function _worker at 0x7feb5be8ca60>
    └ <Thread(ThreadPoolExecutor-0_0, started 140648835726136)>
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7feb5be8cb80>
    └ <concurrent.futures.thread._WorkItem object at 0x7feb5b7455b0>
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7feb5b7455b0>
             │    │   │    └ (<Job (id=6623f85a653f47dbbb94ad2ca61c8a13 name=run)>, 'default', [datetime.datetime(2024, 1, 16, 2, 0, tzinfo=zoneinfo.ZoneI...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7feb5b7455b0>
             │    └ <function run_job at 0x7feb5bfaa820>
             └ <concurrent.futures.thread._WorkItem object at 0x7feb5b7455b0>
  File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             │   │     │   │       │   └ <member 'kwargs' of 'Job' objects>
             │   │     │   │       └ <Job (id=6623f85a653f47dbbb94ad2ca61c8a13 name=run)>
             │   │     │   └ <member 'args' of 'Job' objects>
             │   │     └ <Job (id=6623f85a653f47dbbb94ad2ca61c8a13 name=run)>
             │   └ <member 'func' of 'Job' objects>
             └ <Job (id=6623f85a653f47dbbb94ad2ca61c8a13 name=run)>

  File "/app/fansMedalHelper/main.py", line 117, in run
    loop.run_until_complete(main())
    │    │                  └ <function main at 0x7feb5c3c9dc0>
    │    └ <function BaseEventLoop.run_until_complete at 0x7feb5cf85d30>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7feb5cf85ca0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7feb5cf88820>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7feb5d02c5e0>
    └ <Handle <TaskWakeupMethWrapper object at 0x7feb5b7fafa0>(<_GatheringFu... was banned')>)>
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x7feb5b7fafa0>(<_GatheringFu... was banned')>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x7feb5b7fafa0>(<_GatheringFu... was banned')>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x7feb5b7fafa0>(<_GatheringFu... was banned')>)>

> File "/app/fansMedalHelper/src/user.py", line 195, in like_v3
    await asyncio.gather(*allTasks)
          │       │       └ [<coroutine object BiliApi.likeInteractV3 at 0x7feb5baa46c0>, <coroutine object BiliApi.likeInteractV3 at 0x7feb5baa4240>, <c...
          │       └ <function gather at 0x7feb5cf7b040>
          └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>

  File "/app/fansMedalHelper/src/api.py", line 205, in likeInteractV3
    await self.__post(
          └ <src.api.BiliApi object at 0x7feb5b75ea00>

  File "/app/fansMedalHelper/src/api.py", line 73, in wrapper
    raise e

  File "/app/fansMedalHelper/src/api.py", line 62, in wrapper
    result = await func(*args, **kwargs)
                   │     │       └ {'data': {'access_key': '76e2e199a03fb5fb5c2de8fa375165c1', 'actionKey': 'appkey', 'anchor_id': 477332594, 'appkey': '4409e2c...
                   │     └ (<src.api.BiliApi object at 0x7feb5b75ea00>, 'https://api.live.bilibili.com/xlive/app-ucenter/v1/like_info_v3/like/likeReport...
                   └ <function BiliApi.__post at 0x7feb5c3ea670>

  File "/app/fansMedalHelper/src/api.py", line 135, in __post
    return self.__check_response(await resp.json())
           │                           │    └ <function ClientResponse.json at 0x7feb5c519040>
           │                           └ <ClientResponse(https://api.live.bilibili.com/xlive/app-ucenter/v1/like_info_v3/like/likeReportV3) [412 Precondition Failed]>...
           └ <src.api.BiliApi object at 0x7feb5b75ea00>

  File "/app/fansMedalHelper/src/api.py", line 124, in __check_response
    raise BiliApiError(resp['code'], resp['message'])
          │            │             └ {'code': -412, 'message': 'request was banned', 'ttl': 1}
          │            └ {'code': -412, 'message': 'request was banned', 'ttl': 1}
          └ <class 'src.api.BiliApiError'>

src.api.BiliApiError: request was banned
2024-01-16 02:00:01  夜辰哒哒哒  宇佐紀ノノ_usagi 房间弹幕打卡失败: request was banned
2024-01-16 02:00:02  夜辰哒哒哒  白神遥Haruka 步玎Pudding 咩栗 呜米 诺子喵呜 等共 16 个房间的第1次心跳包已发送（1/75）
2024-01-16 02:00:02  夜辰哒哒哒  明月庄主moon的应援团① 签到成功
2024-01-16 02:00:08  夜辰哒哒哒  白神遥Haruka 房间弹幕打卡失败: request was banned
2024-01-16 02:00:08  夜辰哒哒哒  匠拙墨同学的应援团 签到成功
2024-01-16 02:00:14  夜辰哒哒哒  步玎Pudding 房间弹幕打卡失败: request was banned
2024-01-16 02:00:14  夜辰哒哒哒  应援团签到任务完成 2/2
2024-01-16 02:00:20  夜辰哒哒哒  咩栗 房间弹幕打卡失败: request was banned
2024-01-16 02:00:26  夜辰哒哒哒  呜米 房间弹幕打卡失败: request was banned
2024-01-16 02:00:32  夜辰哒哒哒  诺子喵呜 房间弹幕打卡失败: request was banned
2024-01-16 02:00:38  夜辰哒哒哒  明月庄主 房间弹幕打卡失败: request was banned
2024-01-16 02:00:44  夜辰哒哒哒  格林_曼 房间弹幕打卡失败: request was banned
2024-01-16 02:00:51  夜辰哒哒哒  花园Serena 房间弹幕打卡失败: request was banned
2024-01-16 02:00:57  夜辰哒哒哒  浙江大学CC98论坛 房间弹幕打卡失败: request was banned
2024-01-16 02:01:02  夜辰哒哒哒  白神遥Haruka 步玎Pudding 咩栗 呜米 诺子喵呜 等共 16 个房间的第2次心跳包已发送（2/75）
2024-01-16 02:01:03  夜辰哒哒哒  匠拙墨同学 房间弹幕打卡失败: request was banned
2024-01-16 02:01:09  夜辰哒哒哒  浙江大学 房间弹幕打卡失败: request was banned
2024-01-16 02:01:15  夜辰哒哒哒  洛天依 房间弹幕打卡失败: request was banned
2024-01-16 02:01:21  夜辰哒哒哒  优衣先辈 房间弹幕打卡失败: request was banned
2024-01-16 02:01:28  夜辰哒哒哒  璃亚Official 房间弹幕打卡失败: request was banned
2024-01-16 02:01:34  夜辰哒哒哒  天使猫猫酱 房间弹幕打卡失败: request was banned
2024-01-16 02:01:40  夜辰哒哒哒  眞白花音_Official 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  request was banned
Traceback (most recent call last):

> File "/app/fansMedalHelper/main.py", line 87, in main
    await asyncio.gather(*startTasks)
          │       │       └ [<coroutine object BiliUser.start at 0x7feb5be86940>]
          │       └ <function gather at 0x7feb5cf7b040>
          └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>

  File "/app/fansMedalHelper/src/user.py", line 263, in start
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliUser.like_v3 at 0x7feb5baabbc0>, <coroutine object BiliUser.watchinglive at 0x7feb5baabe40>, <coroutin...
          │       └ <function gather at 0x7feb5cf7b040>
          └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>

  File "/app/fansMedalHelper/src/user.py", line 231, in sendDanmaku
    (await self.api.wearMedal(self.initialMedal['medal_id'])) if self.config['WEARMEDAL'] else ...
           │    │   │         │    │                             │    └ {'ASYNC': 1, 'LIKE_CD': 6, 'DANMAKU_CD': 6, 'WATCHINGLIVE': 75, 'WEARMEDAL': 1, 'SIGNINGROUP': 6, 'PROXY': None}
           │    │   │         │    │                             └ <src.user.BiliUser object at 0x7feb5b75e8b0>
           │    │   │         │    └ {'uid': 439240749, 'target_id': 313248263, 'target_name': '宇佐紀ノノ_usagi', 'medal_id': 351972, 'level': 21, 'medal_name': '饲犬员'...
           │    │   │         └ <src.user.BiliUser object at 0x7feb5b75e8b0>
           │    │   └ <function BiliApi.wearMedal at 0x7feb5c3eaca0>
           │    └ <src.api.BiliApi object at 0x7feb5b75ea00>
           └ <src.user.BiliUser object at 0x7feb5b75e8b0>

  File "/app/fansMedalHelper/src/api.py", line 460, in wearMedal
    return await self.__post(
                 └ <src.api.BiliApi object at 0x7feb5b75ea00>

  File "/app/fansMedalHelper/src/api.py", line 73, in wrapper
    raise e

  File "/app/fansMedalHelper/src/api.py", line 62, in wrapper
    result = await func(*args, **kwargs)
                   │     │       └ {'data': {'access_key': '76e2e199a03fb5fb5c2de8fa375165c1', 'actionKey': 'appkey', 'appkey': '4409e2ce8ffd12b8', 'medal_id': ...
                   │     └ (<src.api.BiliApi object at 0x7feb5b75ea00>, 'https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/wear')
                   └ <function BiliApi.__post at 0x7feb5c3ea670>

  File "/app/fansMedalHelper/src/api.py", line 135, in __post
    return self.__check_response(await resp.json())
           │                           │    └ <function ClientResponse.json at 0x7feb5c519040>
           │                           └ <ClientResponse(https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/wear) [412 Precondition Failed]>
           │                             <CIMultiDictPro...
           └ <src.api.BiliApi object at 0x7feb5b75ea00>

  File "/app/fansMedalHelper/src/api.py", line 124, in __check_response
    raise BiliApiError(resp['code'], resp['message'])
          │            │             └ {'code': -412, 'message': 'request was banned', 'ttl': 1}
          │            └ {'code': -412, 'message': 'request was banned', 'ttl': 1}
          └ <class 'src.api.BiliApiError'>

src.api.BiliApiError: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  任务执行失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 签到成功,本月签到次数: 15/31
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 UL等级: 12 ,还差 748694 经验升级
2024-01-16 02:01:46  B站粉丝牌助手   应援团签到任务完成 2/2
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 今日亲密度获取情况如下（20级以下）：
2024-01-16 02:01:46  B站粉丝牌助手  【1200以下】白神遥Haruka 步玎Pudding 咩栗 呜米 诺子喵呜等 16个
2024-01-16 02:01:46  B站粉丝牌助手  【当前佩戴】「饲犬员」(宇佐紀ノノ_usagi) 21 级 
2024-01-16 02:01:46  B站粉丝牌助手  错误日志：
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 点赞任务异常,请检查日志
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 宇佐紀ノノ_usagi 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 白神遥Haruka 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 步玎Pudding 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 咩栗 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 呜米 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 诺子喵呜 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 明月庄主 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 格林_曼 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 花园Serena 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 浙江大学CC98论坛 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 匠拙墨同学 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 浙江大学 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 洛天依 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 优衣先辈 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 璃亚Official 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 天使猫猫酱 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  【夜辰哒哒哒】 眞白花音_Official 房间弹幕打卡失败: request was banned
2024-01-16 02:01:46  B站粉丝牌助手  ---
2024-01-16 02:01:46  B站粉丝牌助手  dingtalk 已推送
2024-01-16 02:01:46  B站粉丝牌助手  任务结束，等待下一次执行。
```

**Comment by Gensokyo1995** [comment]
一样，弹幕打卡失败，估计接口又换了

**Comment by 495fd** [comment]
同，今天突然就不能打卡了

**Comment by SysuCodeRookie** [comment]
同问

**Comment by Memorywzd** [comment]
相同问题，昨天一切正常，今日出现上述同类报错

**Comment by baobao521o** [comment]
我也是同样情况

**Comment by CatOverrun** [comment]
同。
之前用uids批量查直播间信息的的api，大概是去年10月左右，也是这样返回412，而且是多个服务器同时，所以应该是阿b那边，这个api暂停使用了。

**Comment by BlackSpacee** [comment]
同。但我得到了1400，不是满的

**Comment by XiaoMiku01** [comment]
0.3.8 已修复

**Comment by baobao521o** [comment]
> 我也是同样情况



> 0.3.8 已修复
怎么在自己运行界面升级到0.3.8呢？我的还是过去版本呢

**Comment by XiaoMiku01** [comment]
看文档 不会的就全删了重新部署

**Comment by gy39830** [comment]
> 0.3.8 已修复

![image](https://github.com/XiaoMiku01/fansMedalHelper/assets/60922309/5ee0a737-a602-4743-895a-ba5fb394f4ce)
0.3.8 点赞有点问题

**Comment by XiaoMiku01** [comment]
你改我代码了？怎么和我的代码不一样 https://github.com/XiaoMiku01/fansMedalHelper/blob/906ec58db2c540d149a271cf5d2884d58cd18b34/src/user.py#L193

**Comment by gy39830** [comment]
> 你改我代码了？怎么和我的代码不一样
> 
> https://github.com/XiaoMiku01/fansMedalHelper/blob/906ec58db2c540d149a271cf5d2884d58cd18b34/src/user.py#L193

没改，只是没有全覆盖更新
