### ISSUE TITLE
[Bug]: API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常

### ISSUE THREAD

**Issue by sst2020** [XiaoMiku01/fansMedalHelper#164]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.8

### 运行环境

Windows (64)

### 运行架构

x86

### 部署方式

本地

### 粉丝牌数量

1

### 日志记录（可选）

```python
2024-01-21 10:31:16  xx  xx 等共 1 个房间的第9次心跳包已发送（9/65）
2024-01-21 10:32:16  xx  xx 等共 1 个房间的第10次心跳包已发送（10/65）
2024-01-21 10:33:17  xx  xx 等共 1 个房间的第11次心跳包已发送（11/65）
API /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: 
2024-01-21 10:34:32  B站粉丝牌助手  
Traceback (most recent call last):

  File "F:\hsy\JetBrains\Pycharm\plugins\python\helpers\pydev\pydevd.py", line 2235, in <module>
    main()
    └ <function main at 0x0000000003E3C5E0>

  File "F:\hsy\JetBrains\Pycharm\plugins\python\helpers\pydev\pydevd.py", line 2217, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 55190, 'vm_type': None, 'client': '127.0.0.1', 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': Fal...
              │        └ <function PyDB.run at 0x0000000003E37380>
              └ <__main__.PyDB object at 0x000000000082B890>

  File "F:\hsy\JetBrains\Pycharm\plugins\python\helpers\pydev\pydevd.py", line 1527, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            └ 'F:\\hsy\\fansMedalHelper\\main.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x0000000003E37420>
           └ <__main__.PyDB object at 0x000000000082B890>

  File "F:\hsy\JetBrains\Pycharm\plugins\python\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        └ 'F:\\hsy\\fansMedalHelper\\main.py'
    │             └ <function execfile at 0x00000000039680E0>
    └ <module '_pydev_bundle.pydev_imports' from 'F:\\hsy\\JetBrains\\Pycharm\\plugins\\python\\helpers\\pydev\\_pydev_bundle\\pyde...

  File "F:\hsy\JetBrains\Pycharm\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              └ 'F:\\hsy\\fansMedalHelper\\main.py'
                 └ 'import json\nimport os\nimport sys\nfrom loguru import logger\nimport warnings\nimport asyncio\nimport aiohttp\nimport itert...

  File "F:\hsy\fansMedalHelper\main.py", line 157, in <module>
    loop.run_until_complete(main())
    │    │                  └ <function main at 0x0000000004B651C0>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000000003DA94E0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "D:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000000003E1A520>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\ProgramData\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000000003DAB240>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000000003CF7F60>
    └ <Handle Task.task_wakeup(<_GatheringFu...imeoutError()>)>
  File "D:\ProgramData\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<_GatheringFu...imeoutError()>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<_GatheringFu...imeoutError()>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<_GatheringFu...imeoutError()>)>

> File "F:\hsy\fansMedalHelper\main.py", line 87, in main
    await asyncio.gather(*startTasks)
          │       │       └ [<coroutine object BiliUser.start at 0x0000000004B4D3F0>]
          │       └ <function gather at 0x0000000003DA07C0>
          └ <module 'asyncio' from 'D:\\ProgramData\\anaconda3\\Lib\\asyncio\\__init__.py'>

  File "F:\hsy\fansMedalHelper\src\user.py", line 263, in start
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliUser.like_v3 at 0x0000000004B61690>, <coroutine object BiliUser.watchinglive at 0x0000000004A7EC00>, <...
          │       └ <function gather at 0x0000000003DA07C0>
          └ <module 'asyncio' from 'D:\\ProgramData\\anaconda3\\Lib\\asyncio\\__init__.py'>

  File "F:\hsy\fansMedalHelper\src\user.py", line 322, in watchinglive
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliApi.heartbeat at 0x0000000004A7F100>]
          │       └ <function gather at 0x0000000003DA07C0>
          └ <module 'asyncio' from 'D:\\ProgramData\\anaconda3\\Lib\\asyncio\\__init__.py'>

  File "F:\hsy\fansMedalHelper\src\api.py", line 429, in heartbeat
    return await self.__post(url, data=SingableDict(data).signed, headers=self.headers)
                 │           │         │            │                     │    └ {'User-Agent': 'Mozilla/5.0 BiliDroid/6.73.1 (bbcallen@gmail.com) os/android model/Mi 10 Pro mobi_app/android build/6731100 c...
                 │           │         │            │                     └ <src.api.BiliApi object at 0x0000000004BA0D90>
                 │           │         │            └ {'platform': 'android', 'uuid': '2cfbb1cd-1311-4d1d-b212-5ae008ec30c2', 'buvid': 'MAY7FE2T5WZHVULLOXQ1SZESWTOMYQCB3RIKF', 'se...
                 │           │         └ <class 'src.api.SingableDict'>
                 │           └ 'https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBeat'
                 └ <src.api.BiliApi object at 0x0000000004BA0D90>

  File "F:\hsy\fansMedalHelper\src\api.py", line 75, in wrapper
    raise e

  File "F:\hsy\fansMedalHelper\src\api.py", line 61, in wrapper
    result = await func(*args, **kwargs)
                   │     │       └ {'data': {'access_key': '24264de4ffeec8a55977a3f623a1da11', 'actionKey': 'appkey', 'appkey': '4409e2ce8ffd12b8', 'area_id': '...
                   │     └ (<src.api.BiliApi object at 0x0000000004BA0D90>, 'https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHea...
                   └ <function BiliApi.__post at 0x0000000004AC0180>

  File "F:\hsy\fansMedalHelper\src\api.py", line 135, in __post
    async with self.session.post(*args, **kwargs) as resp:
               │    │       │     │       └ {'data': {'access_key': '24264de4ffeec8a55977a3f623a1da11', 'actionKey': 'appkey', 'appkey': '4409e2ce8ffd12b8', 'area_id': '...
               │    │       │     └ ('https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBeat',)
               │    │       └ <function ClientSession.post at 0x0000000004AA8720>
               │    └ <aiohttp.client.ClientSession object at 0x0000000004BA2E10>
               └ <src.api.BiliApi object at 0x0000000004BA0D90>

  File "F:\hsy\fansMedalHelper\venv\Lib\site-packages\aiohttp\client.py", line 1187, in __aenter__
    self._resp = await self._coro
    │    │             │    └ <member '_coro' of '_BaseRequestContextManager' objects>
    │    │             └ <aiohttp.client._RequestContextManager object at 0x0000000004B7A110>
    │    └ <member '_resp' of '_BaseRequestContextManager' objects>
    └ <aiohttp.client._RequestContextManager object at 0x0000000004B7A110>
  File "F:\hsy\fansMedalHelper\venv\Lib\site-packages\aiohttp\client.py", line 500, in _request
    with timer:
         └ <aiohttp.helpers.TimerContext object at 0x0000000004BE2B50>
  File "F:\hsy\fansMedalHelper\venv\Lib\site-packages\aiohttp\helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
          │       └ <class 'TimeoutError'>
          └ <module 'asyncio' from 'D:\\ProgramData\\anaconda3\\Lib\\asyncio\\__init__.py'>

TimeoutError
2024-01-21 10:34:33  B站粉丝牌助手  任务执行失败: 
2024-01-21 10:34:33  B站粉丝牌助手  【xx】 UL等级: xx,还差 xx 经验升级
2024-01-21 10:34:33  B站粉丝牌助手  【xx】 弹幕打卡任务完成 1/1
2024-01-21 10:34:33  B站粉丝牌助手  【xx】 今日亲密度获取情况如下（20级以下）：
2024-01-21 10:34:33  B站粉丝牌助手  【1200以下】xx 1个
```

### 补充说明（可选）

已经连续多天出现
**_已尝试解决方法_**：重新登陆；重新配置等均无效

**Comment by baobao521o** [comment]
![mmexport1677843012215](https://github.com/XiaoMiku01/fansMedalHelper/assets/156780956/5ae63b47-63ca-4f8f-9307-e4dd480a5722)
宿迁云服务器还是登录不了

**Comment by baobao521o** [comment]
宿迁云服务器还是登陆不了
![AL 3XZET4O33QU1@@N_~F8L](https://github.com/XiaoMiku01/fansMedalHelper/assets/156780956/0e999ae2-d7d6-4243-8c38-2f0b823eb26e)

**Comment by XiaoMiku01** [comment]
换服务器
