### ISSUE TITLE
[Bug]: 这几天总是时不时的提示连接失败

### ISSUE THREAD

**Issue by liuqingshui001** [XiaoMiku01/fansMedalHelper#169]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.8

### 运行环境

其它（请在下方说明）

### 运行架构

None

### 部署方式

其它（请在下方说明）

### 粉丝牌数量

22

### 日志记录（可选）

```python
异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Try again][0m
[32m2024-01-31 11:55:08[0m [34m B站粉丝牌助手 [0m [31m[1mCannot connect to host live-trace.bilibili.com:443 ssl:default [Try again][0m
[33m[1mTraceback (most recent call last):[0m

  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1155, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
                  │       │      └ <Task finished name='Task-224' coro=<TCPConnector._resolve_host() done, defined at /usr/local/lib/python3.10/site-packages/ai...
                  │       └ <function shield at 0x7f6062932320>
                  └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1160, in drop_exception
    fut.result()
    │   └ <method 'result' of '_asyncio.Task' objects>
    └ <Task finished name='Task-158' coro=<TCPConnector._resolve_host() done, defined at /usr/local/lib/python3.10/site-packages/ai...
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 861, in _resolve_host
    await event.wait()
          │     └ <function EventResultOrError.wait at 0x7f6061fc4c10>
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/locks.py", line 34, in wait
    raise self._exc
          │    └ gaierror(-3, 'Try again')
          └ <aiohttp.locks.EventResultOrError object at 0x7f6061dd3df0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1160, in drop_exception
    fut.result()
    │   └ <method 'result' of '_asyncio.Task' objects>
    └ <Task finished name='Task-136' coro=<TCPConnector._resolve_host() done, defined at /usr/local/lib/python3.10/site-packages/ai...
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
                  │    │         │       │     │            │    └ 0
                  │    │         │       │     │            └ <aiohttp.connector.TCPConnector object at 0x7f6061dd1ab0>
                  │    │         │       │     └ 443
                  │    │         │       └ 'live-trace.bilibili.com'
                  │    │         └ <function ThreadedResolver.resolve at 0x7f6061fc5000>
                  │    └ <aiohttp.resolver.ThreadedResolver object at 0x7f6061dd19f0>
                  └ <aiohttp.connector.TCPConnector object at 0x7f6061dd1ab0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
                  │    │     └ <function BaseEventLoop.getaddrinfo at 0x7f606293f6d0>
                  │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
                  └ <aiohttp.resolver.ThreadedResolver object at 0x7f6061dd19f0>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
                 │    └ <function BaseEventLoop.run_in_executor at 0x7f606293f520>
                 └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │        │            └ None
             │        └ None
             └ None
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               │       │           │     │     │       │     │      └ <AddressInfo.AI_ADDRCONFIG: 32>
               │       │           │     │     │       │     └ 0
               │       │           │     │     │       └ <SocketKind.SOCK_STREAM: 1>
               │       │           │     │     └ 0
               │       │           │     └ 443
               │       │           └ 'live-trace.bilibili.com'
               │       └ <built-in function getaddrinfo>
               └ <module '_socket' from '/usr/local/lib/python3.10/lib-dynload/_socket.cpython-310-x86_64-linux-gnu.so'>

[31m[1msocket.gaierror[0m:[1m [Errno -3] Try again[0m


[1mThe above exception was the direct cause of the following exception:[0m


[33m[1mTraceback (most recent call last):[0m

  File "[32m/ql/data/scripts/fansMedalHelper/[0m[32m[1mindex.py[0m", line [33m17[0m, in [35m<module>[0m
    [1mrun[0m[1m([0m[1m)[0m
    [36m└ [0m[36m[1m<function run at 0x7f6061df08b0>[0m

  File "[32m/ql/data/scripts/fansMedalHelper/[0m[32m[1mmain.py[0m", line [33m117[0m, in [35mrun[0m
    [1mloop[0m[35m[1m.[0m[1mrun_until_complete[0m[1m([0m[1mmain[0m[1m([0m[1m)[0m[1m)[0m
    [36m│    │                  └ [0m[36m[1m<function main at 0x7f6061df0430>[0m
    [36m│    └ [0m[36m[1m<function BaseEventLoop.run_until_complete at 0x7f606293ed40>[0m
    [36m└ [0m[36m[1m<_UnixSelectorEventLoop running=True closed=False debug=False>[0m

  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f606293ecb0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f606294c820>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f606304c1f0>
    └ <Handle Task.task_wakeup(<_GatheringFu...'Try again'))>)>
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<_GatheringFu...'Try again'))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<_GatheringFu...'Try again'))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<_GatheringFu...'Try again'))>)>

> File "[32m/ql/data/scripts/fansMedalHelper/[0m[32m[1mmain.py[0m", line [33m87[0m, in [35mmain[0m
    [35m[1mawait[0m [1masyncio[0m[35m[1m.[0m[1mgather[0m[1m([0m[35m[1m*[0m[1mstartTasks[0m[1m)[0m
    [36m      │       │       └ [0m[36m[1m[<coroutine object BiliUser.start at 0x7f6061daa730>][0m
    [36m      │       └ [0m[36m[1m<function gather at 0x7f6062932170>[0m
    [36m      └ [0m[36m[1m<module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>[0m

  File "[32m/ql/data/scripts/fansMedalHelper/src/[0m[32m[1muser.py[0m", line [33m263[0m, in [35mstart[0m
    [35m[1mawait[0m [1masyncio[0m[35m[1m.[0m[1mgather[0m[1m([0m[35m[1m*[0m[1mtasks[0m[1m)[0m
    [36m      │       │       └ [0m[36m[1m[<coroutine object BiliUser.like_v3 at 0x7f6061dab8b0>, <coroutine object BiliUser.watchinglive at 0x7f6061daaa40>, <coroutin...[0m
    [36m      │       └ [0m[36m[1m<function gather at 0x7f6062932170>[0m
    [36m      └ [0m[36m[1m<module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>[0m

  File "[32m/ql/data/scripts/fansMedalHelper/src/[0m[32m[1muser.py[0m", line [33m322[0m, in [35mwatchinglive[0m
    [35m[1mawait[0m [1masyncio[0m[35m[1m.[0m[1mgather[0m[1m([0m[35m[1m*[0m[1mtasks[0m[1m)[0m
    [36m      │       │       └ [0m[36m[1m[<coroutine object BiliApi.heartbeat at 0x7f6061dab920>, <coroutine object BiliApi.heartbeat at 0x7f6061daaea0>, <coroutine o...[0m
    [36m      │       └ [0m[36m[1m<function gather at 0x7f6062932170>[0m
    [36m      └ [0m[36m[1m<module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>[0m

  File "[32m/ql/data/scripts/fansMedalHelper/src/[0m[32m[1mapi.py[0m", line [33m429[0m, in [35mheartbeat[0m
    [35m[1mreturn[0m [35m[1mawait[0m [1mself[0m[35m[1m.[0m[1m__post[0m[1m([0m[1murl[0m[1m,[0m [1mdata[0m[35m[1m=[0m[1mSingableDict[0m[1m([0m[1mdata[0m[1m)[0m[35m[1m.[0m[1msigned[0m[1m,[0m [1mheaders[0m[35m[1m=[0m[1mself[0m[35m[1m.[0m[1mheaders[0m[1m)[0m
    [36m             │           │         │            │                     │    └ [0m[36m[1m{'User-Agent': 'Mozilla/5.0 BiliDroid/6.73.1 (bbcallen@gmail.com) os/android model/Mi 10 Pro mobi_app/android build/6731100 c...[0m
    [36m             │           │         │            │                     └ [0m[36m[1m<src.api.BiliApi object at 0x7f6061dd1bd0>[0m
    [36m             │           │         │            └ [0m[36m[1m{'platform': 'android', 'uuid': 'b1f25c7c-79af-4eef-af8c-3f795fcf57d0', 'buvid': 'VNRBU3QXGSJJUKCWP05EDF1XOZH46YAFML2TQ', 'se...[0m
    [36m             │           │         └ [0m[36m[1m<class 'src.api.SingableDict'>[0m
    [36m             │           └ [0m[36m[1m'https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBeat'[0m
    [36m             └ [0m[36m[1m<src.api.BiliApi object at 0x7f6061dd1bd0>[0m

  File "[32m/ql/data/scripts/fansMedalHelper/src/[0m[32m[1mapi.py[0m", line [33m75[0m, in [35mwrapper[0m
    [35m[1mraise[0m [1me[0m

  File "[32m/ql/data/scripts/fansMedalHelper/src/[0m[32m[1mapi.py[0m", line [33m61[0m, in [35mwrapper[0m
    [1mresult[0m [35m[1m=[0m [35m[1mawait[0m [1mfunc[0m[1m([0m[35m[1m*[0m[1margs[0m[1m,[0m [35m[1m**[0m[1mkwargs[0m[1m)[0m
    [36m               │     │       └ [0m[36m[1m{'data': {'access_key': '8ec07b9c880bf9d0084c9baf53807d82', 'actionKey': 'appkey', 'appkey': '4409e2ce8ffd12b8', 'area_id': '...[0m
    [36m               │     └ [0m[36m[1m(<src.api.BiliApi object at 0x7f6061dd1bd0>, 'https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBe...[0m
    [36m               └ [0m[36m[1m<function BiliApi.__post at 0x7f6061d69fc0>[0m

  File "[32m/ql/data/scripts/fansMedalHelper/src/[0m[32m[1mapi.py[0m", line [33m135[0m, in [35m__post[0m
    [35m[1masync[0m [35m[1mwith[0m [1mself[0m[35m[1m.[0m[1msession[0m[35m[1m.[0m[1mpost[0m[1m([0m[35m[1m*[0m[1margs[0m[1m,[0m [35m[1m**[0m[1mkwargs[0m[1m)[0m [35m[1mas[0m [1mresp[0m[1m:[0m
    [36m           │    │       │     │       └ [0m[36m[1m{'data': {'access_key': '8ec07b9c880bf9d0084c9baf53807d82', 'actionKey': 'appkey', 'appkey': '4409e2ce8ffd12b8', 'area_id': '...[0m
    [36m           │    │       │     └ [0m[36m[1m('https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBeat',)[0m
    [36m           │    │       └ [0m[36m[1m<function ClientSession.post at 0x7f6061d5e680>[0m
    [36m           │    └ [0m[36m[1m<aiohttp.client.ClientSession object at 0x7f6061dd1810>[0m
    [36m           └ [0m[36m[1m<src.api.BiliApi object at 0x7f6061dd1bd0>[0m

  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
    │    │             │    └ <member '_coro' of '_BaseRequestContextManager' objects>
    │    │             └ <aiohttp.client._RequestContextManager object at 0x7f6061dd2f20>
    │    └ <member '_resp' of '_BaseRequestContextManager' objects>
    └ <aiohttp.client._RequestContextManager object at 0x7f6061dd2f20>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
                 │    │          └ <function BaseConnector.connect at 0x7f6061fc63b0>
                 │    └ <aiohttp.connector.TCPConnector object at 0x7f6061dd1ab0>
                 └ <aiohttp.client.ClientSession object at 0x7f6061dd1810>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
                  │    │                  │    │       └ ClientTimeout(total=3, connect=None, sock_read=None, sock_connect=None)
                  │    │                  │    └ []
                  │    │                  └ <aiohttp.client_reqrep.ClientRequest object at 0x7f6061dd3ca0>
                  │    └ <function TCPConnector._create_connection at 0x7f6061fc6e60>
                  └ <aiohttp.connector.TCPConnector object at 0x7f6061dd1ab0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
                     │    │                         │    │       └ ClientTimeout(total=3, connect=None, sock_read=None, sock_connect=None)
                     │    │                         │    └ []
                     │    │                         └ <aiohttp.client_reqrep.ClientRequest object at 0x7f6061dd3ca0>
                     │    └ <function TCPConnector._create_direct_connection at 0x7f6061fc7490>
                     └ <aiohttp.connector.TCPConnector object at 0x7f6061dd1ab0>
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1169, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
          │                    │   └ <property object at 0x7f6061fa6d90>
          │                    └ <aiohttp.client_reqrep.ClientRequest object at 0x7f6061dd3ca0>
          └ <class 'aiohttp.client_exceptions.ClientConnectorError'>

[31m[1maiohttp.client_exceptions.ClientConnectorError[0m:[1m Cannot connect to host live-trace.bilibili.com:443 ssl:default [Try again][0m
```

### 补充说明（可选）

  青龙面板部署的    有时候连接失败   有时候又正常   但是我自家的网络应该是一直畅通的

**Comment by XiaoMiku01** [comment]
有没有广告屏蔽插件把这个域名拦截了live-trace.bilibili.com

**Comment by liuqingshui001** [comment]
> 有没有广告屏蔽插件把这个域名拦截了live-trace.bilibili.com

没有广告屏蔽插件  而且他是这种   正常发送了一段时间心跳包之后 就突然无法连接了
第30次心跳包已发送（30/75）[0m
[32m2024-01-31 13:21:15[0m [34m 流清水水笔 [0m [1m杜松子_Gin 明前奶绿 嘉然今天吃什么 乃琳Queen 贝拉kira 等共 22 个房间的第31次心跳包已发送（31/75）[0m
[32m2024-01-31 13:22:15[0m [34m 流清水水笔 [0m [1m杜松子_Gin 明前奶绿 嘉然今天吃什么 乃琳Queen 贝拉kira 等共 22 个房间的第32次心跳包已发送（32/75）[0m
[32m2024-01-31 13:23:16[0m [34m 流清水水笔 [0m [1m杜松子_Gin 明前奶绿 嘉然今天吃什么 乃琳Queen 贝拉kira 等共 22 个房间的第33次心跳包已发送（33/75）[0m
[32m2024-01-31 13:24:16[0m [34m 流清水水笔 [0m [1m杜松子_Gin 明前奶绿 嘉然今天吃什么 乃琳Queen 贝拉kira 等共 22 个房间的第34次心跳包已发送（34/75）[0m
[32m2024-01-31 13:25:28[0m [34m 流清水水笔 [0m [31m[1mAPI /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Try again][0m
[32m2024-01-31 13:25:28[0m [34m 流清水水笔 [0m [31m[1mAPI /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Try again][0m
[32m2024-01-31 13:25:28[0m [34m 流清水水笔 [0m [31m[1mAPI /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Try again][0m
[32m2024-01-31 13:25:28[0m [34m 流清水水笔 [0m [31m[1mAPI /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Try again][0m
[32m2024-01-31 13:25:28[0m [34m 流清水水笔 [0m [31m[1mAPI /xlive/data-interface/v1/heartbeat/mobileHeartBeat 调用出现异常: Cannot connect to host live-trace.bilibili.com:443 ssl:default [Try again][0m

**Comment by liuqingshui001** [comment]
可能找到原因了   狗屎的联通宽带给我上传限速到3mbps     我平时玩pt   我去找他们对线去
