### ISSUE TITLE
白名单报错

### ISSUE THREAD

**Issue by Malus-Mill** [XiaoMiku01/fansMedalHelper#63]
Windows PowerShell
版权所有（C） Microsoft Corporation。保留所有权利。

安装最新的 PowerShell，了解新功能和改进！https://aka.ms/PSWindows

PS D:\新粉丝牌\fansMedalHelper> python main.py
2022-06-30 22:34:54  B站粉丝牌助手  外部调用,开启任务
2022-06-30 22:34:54  B站粉丝牌助手  当前版本为: 0.3.4
2022-06-30 22:34:54  Malus-Mill  15567746 登录成功
2022-06-30 22:34:55  Malus-Mill  今日已签到过,无法重复签到
2022-06-30 22:34:55  Malus-Mill  当前用户UL等级: 37 ,还差 19167999 经验升级
2022-06-30 22:34:58  Malus-Mill  弹幕打卡任务开始....(预计 0 秒完成)
2022-06-30 22:34:58  Malus-Mill  弹幕打卡任务完成
2022-06-30 22:34:58  Malus-Mill  同步点赞、分享任务开始....
2022-06-30 22:34:58  Malus-Mill  应援团签到任务关闭
2022-06-30 22:34:58  Malus-Mill  每日30分钟任务关闭
2022-06-30 22:35:12  Malus-Mill  点赞、分享任务完成
2022-06-30 22:35:12  Malus-Mill  20级以下牌子共 0 个,完成任务 0 个亲密度大于等于1100
2022-06-30 22:35:12  Malus-Mill  小于1100或失败房间: ... 0个
2022-06-30 22:35:12  Malus-Mill  点赞、分享任务异常
Traceback (most recent call last):

  File "D:\新粉丝牌\fansMedalHelper\main.py", line 118, in <module>
    loop.run_until_complete(main())
    │    │                  └ <function main at 0x0000016F345F92D0>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000016F33737D90>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000016F337F8550>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000016F33749870>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000016F31EE8670>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

> File "D:\新粉丝牌\fansMedalHelper\src\user.py", line 133, in asynclikeandShare
    if len(finallyMedals) / len(self.medalsLower20) <= 0.9:
           │                    │    └ []
           │                    └ <src.user.BiliUser object at 0x0000016F345E8940>
           └ []

ZeroDivisionError: division by zero
2022-06-30 22:35:15  B站粉丝牌助手  【Malus-Mill】 UL等级: 37 ,还差 19167999 经验升级
2022-06-30 22:35:15  B站粉丝牌助手  【Malus-Mill】 弹幕打卡任务完成 0/0
2022-06-30 22:35:15  B站粉丝牌助手  【Malus-Mill】 今日亲密度获取情况如下（20级以下）：
2022-06-30 22:35:15  B站粉丝牌助手  错误日志：
2022-06-30 22:35:15  B站粉丝牌助手  【Malus-Mill】今日已签到过,无法重复签到
2022-06-30 22:35:15  B站粉丝牌助手  【Malus-Mill】 点赞、分享任务异常,请检查日志
2022-06-30 22:35:15  B站粉丝牌助手  ---
2022-06-30 22:35:16  B站粉丝牌助手  An error has been caught in function '_run', process 'MainProcess' (14992), thread 'MainThread' (14768):
Traceback (most recent call last):

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
                 │    │     │                  │       └ {'ssl': <ssl.SSLContext object at 0x0000016F34593DC0>, 'family': <AddressFamily.AF_INET: 2>, 'proto': 0, 'flags': <AddressInf...
                 │    │     │                  └ (functools.partial(<class 'aiohttp.client_proto.ResponseHandler'>, loop=<ProactorEventLoop running=True closed=False debug=Fa...
                 │    │     └ <function BaseEventLoop.create_connection at 0x0000016F33748B80>
                 │    └ <ProactorEventLoop running=True closed=False debug=False>
                 └ <aiohttp.connector.TCPConnector object at 0x0000016F345E9420>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
                                │    └ <function BaseEventLoop._create_connection_transport at 0x0000016F33748C10>
                                └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1119, in _create_connection_transport
    await waiter
          └ <Future finished exception=SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certifica...

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
                       │    │                     └ bytearray(b'\x16\x03\x03\x00A\x02\x00\x00=\x03\x03\x08x\x9d\x91\xc4h\xbd6\xd1\xfb\xab\\du\xf2\x80\xa9@\x97=M\x1f\x1e}\xd3\x8d...
                       │    └ None
                       └ <asyncio.sslproto.SSLProtocol object at 0x0000016F3470DDB0>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
    │    │       └ <function SSLObject.do_handshake at 0x0000016F31ED0A60>
    │    └ <ssl.SSLObject object at 0x0000016F3470DCF0>
    └ <asyncio.sslproto._SSLPipe object at 0x0000016F3470DD20>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 974, in do_handshake
    self._sslobj.do_handshake()
    │    │       └ <method 'do_handshake' of '_ssl._SSLSocket' objects>
    │    └ <_ssl._SSLSocket object at 0x0000016F34680FC0>
    └ <ssl.SSLObject object at 0x0000016F3470DCF0>

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "D:\新粉丝牌\fansMedalHelper\main.py", line 118, in <module>
    loop.run_until_complete(main())
    │    │                  └ <function main at 0x0000016F345F92D0>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000016F33737D90>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000016F337F8550>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000016F33749870>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000016F31EE8670>
    └ <Handle Task.task_wakeup(<Future finis..._ssl.c:997)')>)>

> File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis..._ssl.c:997)')>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis..._ssl.c:997)')>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis..._ssl.c:997)')>)>

  File "D:\新粉丝牌\fansMedalHelper\main.py", line 80, in main
    await push_message(session, users['SENDKEY'], "  \n".join(messageList))
          │            │        │                             └ ['【Malus-Mill】 UL等级: 37 ,还差 19167999 经验升级', ' 【Malus-Mill】 弹幕打卡任务完成 0/0', '【Malus-Mill】 今日亲密度获取情况如下（20级以下）：', '错误日志：', '【Malus...
          │            │        └ {'USERS': [{'white_uid': '21693691,21545232,21219990,9389401,21463227,21671...
          │            └ <aiohttp.client.ClientSession object at 0x0000016F345E9CF0>
          └ <function push_message at 0x0000016F34605870>

  File "D:\新粉丝牌\fansMedalHelper\main.py", line 99, in push_message
    await session.post(url, data=data)
          │       │    │         └ {'title': '【B站粉丝牌助手推送】', 'desp': '【Malus-Mill】 UL等级: 37 ,还差 19167999 经验升级  \n【Malus-Mill】 弹幕打卡任务完成 0/0  \n【Malus-Mill】 今日亲密度获...
          │       │    └ 'https://sctapi.ftqq.com/SCT150904TfYfPOqUPcHqCViVpCtCQud1Q.send'
          │       └ <function ClientSession.post at 0x0000016F3422F370>
          └ <aiohttp.client.ClientSession object at 0x0000016F345E9CF0>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
                 │    │          └ <function BaseConnector.connect at 0x0000016F3418B250>
                 │    └ <aiohttp.connector.TCPConnector object at 0x0000016F345E9420>
                 └ <aiohttp.client.ClientSession object at 0x0000016F345E9CF0>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
                  │    │                  │    │       └ ClientTimeout(total=300, connect=None, sock_read=None, sock_connect=None)
                  │    │                  │    └ []
                  │    │                  └ <aiohttp.client_reqrep.ClientRequest object at 0x0000016F3470DAE0>
                  │    └ <function TCPConnector._create_connection at 0x0000016F3418BD00>
                  └ <aiohttp.connector.TCPConnector object at 0x0000016F345E9420>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
                     │    │                         │    │       └ ClientTimeout(total=300, connect=None, sock_read=None, sock_connect=None)
                     │    │                         │    └ []
                     │    │                         └ <aiohttp.client_reqrep.ClientRequest object at 0x0000016F3470DAE0>
                     │    └ <function TCPConnector._create_direct_connection at 0x0000016F341A83A0>
                     └ <aiohttp.connector.TCPConnector object at 0x0000016F345E9420>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
          └ ClientConnectorCertificateError(ConnectionKey(host='sctapi.ftqq.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth...

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                          │    └ <function TCPConnector._wrap_create_connection at 0x0000016F341A8040>
                          └ <aiohttp.connector.TCPConnector object at 0x0000016F345E9420>

  File "C:\Users\Malus Mill\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
          │                               │   └ <property object at 0x0000016F3417DB20>
          │                               └ <aiohttp.client_reqrep.ClientRequest object at 0x0000016F3470DAE0>
          └ <class 'aiohttp.client_exceptions.ClientConnectorCertificateError'>

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host sctapi.ftqq.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')]
2022-06-30 22:35:16  B站粉丝牌助手  任务结束
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000016F345E9CF0>
PS D:\新粉丝牌\fansMedalHelper> ^A

**Comment by ZippyRhys** [comment]
你sendkey露了，编辑一下吧

**Comment by Malus-Mill** [comment]
> 你sendkey露了，编辑一下吧

感谢大佬

**Comment by XiaoMiku01** [comment]
白名单没错，应该是你设置错了。填的是UID 不是房间号
