### ISSUE TITLE
src.api.BiliApiError: bad timestamp request

### ISSUE THREAD

**Issue by trytodupe** [XiaoMiku01/fansMedalHelper#68]
开始运行2秒之后 这个错误出现了40次

> [ERROR] Task exception was never retrieved
future: <Task finished name='Task-91' coro=<BiliApi.heartbeat() done, defined at /code/src/api.py:329> exception=BiliApiError(1012003, 'bad timestamp request,timestamp:1657987142,watchtime:60')>
Traceback (most recent call last):
  File "/code/src/api.py", line 368, in heartbeat
    return await self.__post(
  File "/code/src/api.py", line 73, in wrapper
    raise e
  File "/code/src/api.py", line 62, in wrapper
    result = await func(*args, **kwargs)
  File "/code/src/api.py", line 135, in __post
    return self.__check_response(await resp.json())
  File "/code/src/api.py", line 124, in __check_response
    raise BiliApiError(resp['code'], resp['message'])
src.api.BiliApiError: bad timestamp request,timestamp:1657987142,watchtime:60

**Comment by XiaoMiku01** [comment]
俩个原因，1.粉丝牌太多了，2.网络不好，重新运行试试

**Comment by trytodupe** [comment]
我放云函数运行的 牌子也就十几个
我再试试
