### ISSUE TITLE
Python 3.11 Passing coroutines is forbidden, use tasks explicitly

### ISSUE THREAD

**Issue by Loongphy** [XiaoMiku01/fansMedalHelper#91]
```python
2022-11-06 01:03:01  B站粉丝牌助手  Passing coroutines is forbidden, use tasks explicitly.
Traceback (most recent call last):

  File "/ql/data/scripts/fansMedalHelper/main.py", line 133, in <module>
    loop.run_until_complete(main())
    │    │                  └ <function main at 0x7f71664e3240>
    │    └ <function BaseEventLoop.run_until_complete at 0x7f71670c3ce0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f71670c3c40>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 604, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f71670c5a80>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f7167628040>
    └ <Handle Task.task_wakeup(<_GatheringFu...explicitly.')>)>
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<_GatheringFu...explicitly.')>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<_GatheringFu...explicitly.')>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<_GatheringFu...explicitly.')>)>

> File "/ql/data/scripts/fansMedalHelper/main.py", line 80, in main
    await asyncio.gather(*startTasks)
          │       │       └ [<coroutine object BiliUser.start at 0x7f7165d65540>]
          │       └ <function gather at 0x7f71670aefc0>
          └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>

  File "/ql/data/scripts/fansMedalHelper/src/user.py", line 206, in start
    await asyncio.wait(task)
          │       │    └ [<coroutine object BiliUser.asynclikeandShare at 0x7f7165fbf0d0>, <coroutine object BiliUser.sendDanmaku at 0x7f7165cfe3e0>, ...
          │       └ <function wait at 0x7f71670ae8e0>
          └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>

  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")

TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

**Comment by Loongphy** [comment]
Fixed https://github.com/XiaoMiku01/fansMedalHelper/commit/8d52318223248f7dc792a5586a556cf48c748f3c
