### ISSUE TITLE
任务执行失败提示错误的时间戳请求

### ISSUE THREAD

**Issue by Yuuki-Rin** [XiaoMiku01/fansMedalHelper#95]
群晖6.2的docker容器
具体日志
2022-11-17 00:00:21  B站粉丝牌助手  bad timestamp request,timestamp:1668614356,watchtime:60
Traceback (most recent call last):

> File "/app/fansMedalHelper/main.py", line 80, in main
    await asyncio.gather(*startTasks)
          │       │       └ [<coroutine object BiliUser.start at 0x7f0114f4bd40>]
          │       └ <function gather at 0x7f0116668f70>
          └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>

  File "/app/fansMedalHelper/src/user.py", line 214, in start
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliUser.asynclikeandShare at 0x7f0114f12f40>, <coroutine object BiliUser.sendDanmaku at 0x7f0114f12ec0>, ...
          │       └ <function gather at 0x7f0116668f70>
          └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>

  File "/app/fansMedalHelper/src/user.py", line 272, in watchinglive
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliApi.heartbeat at 0x7f0114683740>, <coroutine object BiliApi.heartbeat at 0x7f01146837c0>, <coroutine o...
          │       └ <function gather at 0x7f0116668f70>
          └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>

  File "/app/fansMedalHelper/src/api.py", line 408, in heartbeat
    return await self.__post(
                 └ <src.api.BiliApi object at 0x7f0115227610>

  File "/app/fansMedalHelper/src/api.py", line 73, in wrapper
    raise e

  File "/app/fansMedalHelper/src/api.py", line 62, in wrapper
    result = await func(*args, **kwargs)
                   │     │       └ {'data': {'access_key': 'f65cde0f78972152cdd1b46714a27ab2', 'actionKey': 'appkey', 'appkey': '1d8b6e7d45233436', 'area_id': '...
                   │     └ (<src.api.BiliApi object at 0x7f0115227610>, 'https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBe...
                   └ <function BiliApi.__post at 0x7f01152c5e50>

  File "/app/fansMedalHelper/src/api.py", line 135, in __post
    return self.__check_response(await resp.json())
           │                           │    └ <function ClientResponse.json at 0x7f01153918b0>
           │                           └ <ClientResponse(https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBeat) [200 OK]>
           │                             <CIMultiDictProx...
           └ <src.api.BiliApi object at 0x7f0115227610>

  File "/app/fansMedalHelper/src/api.py", line 124, in __check_response
    raise BiliApiError(resp['code'], resp['message'])
          │            │             └ {'code': 1012003, 'message': 'bad timestamp request,timestamp:1668614356,watchtime:60', 'ttl': 1, 'data': None}
          │            └ {'code': 1012003, 'message': 'bad timestamp request,timestamp:1668614356,watchtime:60', 'ttl': 1, 'data': None}
          └ <class 'src.api.BiliApiError'>

src.api.BiliApiError: bad timestamp request,timestamp:1668614356,watchtime:60

**Comment by XiaoMiku01** [comment]
docker 外环境测试是否正常

**Comment by Yuuki-Rin** [comment]
> 
理论上docker环境是没有变的
目前docker上的青龙面板可以运行

**Comment by trytodupe** [comment]
这个问题我也出现过不下4次了 昨天和今天还是连续出现的 我都是在gmt 16:00运行的 但是我重新设置了一个临时触发器运行就可以正常运行 跟这个有没有关系

**Comment by shallowwang** [comment]
只要使用内置定时器就会出问题，推送的是
任务执行失败: bad timestamp request,timestamp:1669478347,watchtime:60  
亲密度只领取到200
轩宝救我🤥

**Comment by XiaoMiku01** [comment]
和楼上一样换个时间试试？

**Comment by shallowwang** [comment]
> 和楼上一样换个时间试试？

改成不是零点就好了🤥
