### ISSUE TITLE
api heartbeat: time check failed

### ISSUE THREAD

**Issue by shanmiteko** [XiaoMiku01/fansMedalHelper#98]
```
Traceback (most recent call last):

> File "/app/fansMedalHelper/main.py", line 80, in main
await asyncio.gather(*startTasks)
│       │       └ [<coroutine object BiliUser.start at 0x7fef645c4b40>]
│       └ <function gather at 0x7fef6554ff70>
└ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>

File "/app/fansMedalHelper/src/user.py", line 214, in start
await asyncio.gather(*tasks)
│       │       └ [<coroutine object BiliUser.asynclikeandShare at 0x7fef645c4a40>, <coroutine object BiliUser.sendDanmaku at0x7fef645c4e40>, ...
│       └ <function gather at 0x7fef6554ff70>
└ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>

File "/app/fansMedalHelper/src/user.py", line 272, in watchinglive
await asyncio.gather(*tasks)
│       │       └ [<coroutine object BiliApi.heartbeat at 0x7fef6452f140>, <coroutine object BiliApi.heartbeat at 0x7fef6452f1c0>, <coroutine o...
│       └ <function gather at 0x7fef6554ff70>
└ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>

File "/app/fansMedalHelper/src/api.py", line 408, in heartbeat
return await self.__post(
└ <src.api.BiliApi object at 0x7fef645130a0>

File "/app/fansMedalHelper/src/api.py", line 73, in wrapper
raise e

File "/app/fansMedalHelper/src/api.py", line 62, in wrapper
result = await func(*args, **kwargs)
│     │       └ {'data': {'access_key': '83aef55293f48af89d9094d9051fb971', 'actionKey': 'appkey', 'appkey': '1d8b6e7d45233436', 'area_id': '...
│     └ (<src.api.BiliApi object at 0x7fef645130a0>, 'https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBe...
└ <function BiliApi.__post at 0x7fef64b94e50>

File "/app/fansMedalHelper/src/api.py", line 135, in __post
return self.__check_response(await resp.json())
│                           │    └ <function ClientResponse.json at 0x7fef64c56940>
│                           └ <ClientResponse(https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBeat) [200 OK]>
│                             <CIMultiDictProx...
└ <src.api.BiliApi object at 0x7fef645130a0>

File "/app/fansMedalHelper/src/api.py", line 124, in __check_response
raise BiliApiError(resp['code'], resp['message'])
│            │             └ {'code': 1012002, 'message': 'time check failed', 'ttl': 1, 'data': {'heartbeat_interval': 60, 'timestamp': 1669991870, 'secr...
│            └ {'code': 1012002, 'message': 'time check failed', 'ttl': 1, 'data': {'heartbeat_interval': 60, 'timestamp': 1669991870, 'secr...
└ <class 'src.api.BiliApiError'>

src.api.BiliApiError: time check failed
```

**Comment by XiaoMiku01** [comment]
#95

**Comment by shanmiteko** [comment]
> #95

问题好像不一样，没用定时器手动运行的

**Comment by XiaoMiku01** [comment]
如果是本地运行的话，可能是本地的时间不准导致的，具体原因我也没搞清楚

**Comment by shanmiteko** [comment]
> 如果是本地运行的话，可能是本地的时间不准导致的，具体原因我也没搞清楚

我趣，就是时间的问题，之前可能把自动设置时间关了，重新获取一下就好了
