### ISSUE TITLE
src.api.BiliApiError: 鉴权失败，请联系账号组

### ISSUE THREAD

**Issue by trytodupe** [XiaoMiku01/fansMedalHelper#99]
在昨天和今天云函数调用都出现了这个问题 我今天外部调用也出现了这个问题 结果是大部分牌子都是1300 1400亲密度
这是我这边的问题还是大家都这样？

```
2022-12-07 08:41:46  user  点赞、分享任务异常
Traceback (most recent call last):

  File "E:\fansMedalHelper\main.py", line 133, in <module>
    loop.run_until_complete(main())
    │    │                  └ <function main at 0x0000026E7181B010>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000026E70CC1D80>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000026E70D75A20>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "D:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000026E70CC37F0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000026E6F453250>
    └ <Handle Task.task_wakeup(<_GatheringFu...鉴权失败，请联系账号组')>)>

  File "D:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<_GatheringFu...鉴权失败，请联系账号组')>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<_GatheringFu...鉴权失败，请联系账号组')>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<_GatheringFu...鉴权失败，请联系账号组')>)>

> File "E:\fansMedalHelper\src\user.py", line 121, in asynclikeandShare
    await asyncio.gather(*tasks)
          │       │       └ [<coroutine object BiliApi.likeInteract at 0x0000026E71C083C0>, <coroutine object BiliApi.shareRoom at 0x0000026E71C08430>]
          │       └ <function gather at 0x0000026E70CB11B0>
          └ <module 'asyncio' from 'D:\\Program Files\\Python310\\lib\\asyncio\\__init__.py'>

  File "E:\fansMedalHelper\src\api.py", line 177, in likeInteract
    await self.__post(
          └ <src.api.BiliApi object at 0x0000026E71B749A0>

  File "E:\fansMedalHelper\src\api.py", line 73, in wrapper
    raise e

  File "E:\fansMedalHelper\src\api.py", line 62, in wrapper
    result = await func(*args, **kwargs)
                   │     │       └ {'data': {'access_key': '', 'actionKey': 'appkey', 'appkey': '1d8b6e7d45233436', 'roomid': 24...
                   │     └ (<src.api.BiliApi object at 0x0000026E71B749A0>, 'https://api.live.bilibili.com/xlive/web-ucenter/v1/interact/likeInteract')
                   └ <function BiliApi.__post at 0x0000026E717B41F0>

  File "E:\fansMedalHelper\src\api.py", line 135, in __post
    return self.__check_response(await resp.json())
           │                           │    └ <function ClientResponse.json at 0x0000026E716E89D0>
           │                           └ <ClientResponse(https://api.live.bilibili.com/xlive/web-ucenter/v1/interact/likeInteract) [200 OK]>
           │                             <CIMultiDictProxy('Date':...
           └ <src.api.BiliApi object at 0x0000026E71B749A0>

  File "E:\fansMedalHelper\src\api.py", line 124, in __check_response
    raise BiliApiError(resp['code'], resp['message'])
          │            │             └ {'code': -663, 'message': '鉴权失败，请联系账号组', 'ttl': 1}
          │            └ {'code': -663, 'message': '鉴权失败，请联系账号组', 'ttl': 1}
          └ <class 'src.api.BiliApiError'>

src.api.BiliApiError: 鉴权失败，请联系账号组
```

**Comment by yaolin6666** [comment]
这两天我的调用也出现了这个问题，这两天亲密度获取量也基本都是1300和1400

**Comment by XiaoMiku01** [comment]
具体原因还在查，可能和昨天禁娱有关

**Comment by 6chtom** [comment]
现在已经显示登陆失败了

**Comment by XiaoMiku01** [comment]
点赞失败是因为B站换了接口，我在测试新的接口。登录失败的问题还在排查

**Comment by XiaoMiku01** [comment]
已更新0.3.6版本 [835eba3](https://github.com/XiaoMiku01/fansMedalHelper/commit/835eba39c500f4024c207049af28ff0fbbceeb15)   
使用阿里云0基础部署的会自动拉取代码更新，其他方式更新方法见文档
